### ISSUE TITLE
Use library for dates handling

### ISSUE THREAD

**Issue by robert-orlinski** [robert-orlinski/robertorlinski.pl#13]
Would be good to use some library like [date-fns](https://www.npmjs.com/package/date-fns) for handling dates (for example in `getISOStringFromPublicationDate()` helper).

For instance, I can see that `article:published_time` in [one of the last blog posts's](https://robertorlinski.pl/artykuly/nowa-wersja-robertorlinski.pl) equals 2022-05-22T00:00:00.000Z while on localhost it is 2022-05-21T22:00:00.000Z for the same blog post.

**Comment by grzegorzpokorski** [comment]
I suggested fix this issue without using any external library in PR #14.
