### ISSUE TITLE
Not all menu items are visible on smaller devices in horizontal mode.

### ISSUE THREAD

**Issue by grzegorzpokorski** [robert-orlinski/robertorlinski.pl#6]
### Description:
On some smartphone types when website is displayed in horizontal mode, not all menu items are visible because of screen size.
### Solution:
Adding a css ```overflow-y:scroll``` property to menu items container for mobile view should solve a problem.
### Screenshot:
![issue](https://user-images.githubusercontent.com/27455716/169784968-80c97ef3-2064-443a-8b35-97e496a759f4.png)

**Comment by robert-orlinski** [comment]
Thank you @grzegorzpokorski!

I will look into it in some free time 💪
